<template>
  <div>
    <el-row type="flex" :gutter="20">
      <el-date-picker v-model="month" type="month" placeholder="选择月份区间" style="margin-right:10px;"></el-date-picker>
      <el-button type="primary" icon="el-icon-search" @click="getData">搜索</el-button>
      <el-button type="success" @click="exportExcel">导出数据</el-button>
    </el-row>
    <div id="exceldata">
      <table>
      <tr>
          <td>类别</td>
          <td>指标</td>
          <td>单位</td>
          <td>2018年6月累计</td>
      </tr>
      <tr>
          <td rowspan="10">基本信息</td>
          <td>下属分院家数</td>
          <td>个</td>
          <td></td>
      </tr>
      <tr>
          <td>下属社区机构家数合计</td>
          <td>个</td>
          <td></td>
      </tr>
      <tr>
          <td>其中： 总院下属社区医疗机构数</td>
          <td>个</td>
          <td></td>
      </tr>
      <tr>
          <td>其中： 分院下属社区医疗机构数</td>
          <td>个</td>
          <td></td>
      </tr>
      <tr>
          <td>编制床位合计</td>
          <td>张</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：总院本部编制床位数</td>
          <td>张</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：分院编制床位数</td>
          <td>张</td>
          <td></td>
      </tr>
      <tr>
          <td>开放床位合计</td>
          <td>张</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：总院本部开放床位数</td>
          <td>张</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：分院开放床位数</td>
          <td>张</td>
          <td></td>
      </tr>
      <tr>
          <td rowspan="42">业务量</td>
          <td>门诊人次（不含体检）</td>
          <td>次</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：总院合计</td>
          <td>次</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：总院本部</td>
          <td></td>
          <td></td>
      </tr>
      <tr>
          <td>总院下属社区小计</td>
          <td></td>
          <td></td>
      </tr>
      <tr>
          <td>分院合计</td>
          <td>次</td>
          <td></td>
      </tr>
      <tr>
          <td>机场社区</td>
          <td>次</td>
          <td></td>
      </tr>
      <tr>
          <td>急诊人次</td>
          <td>次</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：总院合计（社区无）</td>
          <td>次</td>
          <td></td>
      </tr>
      <tr>
          <td>分院合计</td>
          <td>次</td>
          <td></td>
      </tr>
      <tr>
          <td>门急诊总量(不含体检)</td>
          <td></td>
          <td></td>
      </tr>
      <tr>
          <td>其中：总院合计</td>
          <td></td>
          <td></td>
      </tr>
      <tr>
          <td>其中：总院本部</td>
          <td></td>
          <td></td>
      </tr>
      <tr>
          <td>总院下属社区小计（含机场）</td>
          <td></td>
          <td></td>
      </tr>
      <tr>
          <td>分院合计</td>
          <td></td>
          <td></td>
      </tr>
      <tr>
          <td>体检人次</td>
          <td>次</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：健康体检人次</td>
          <td>次</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：女工体检人次</td>
          <td>次</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：入职体检人次</td>
          <td>次</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：高考招生体检及其他</td>
          <td>次</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：司机体检</td>
          <td>次</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：其他</td>
          <td>次</td>
          <td></td>
      </tr>
      <tr>
          <td>入院人次</td>
          <td>次</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：总院</td>
          <td>次</td>
          <td></td>
      </tr>
      <tr>
          <td>分院</td>
          <td>次</td>
          <td></td>
      </tr>
      <tr>
          <td>出院人次</td>
          <td>次</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：总院</td>
          <td>次</td>
          <td></td>
      </tr>
      <tr>
          <td>分院</td>
          <td>次</td>
          <td></td>
      </tr>
      <tr>
          <td>开放床位使用率</td>
          <td>%</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：总院</td>
          <td>%</td>
          <td></td>
      </tr>
      <tr>
          <td>分院</td>
          <td>%</td>
          <td></td>
      </tr>
      <tr>
          <td>出院患者平均住院日</td>
          <td>天</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：总院</td>
          <td>天</td>
          <td></td>
      </tr>
      <tr>
          <td>分院</td>
          <td>天</td>
          <td></td>
      </tr>
      <tr>
          <td>医保平均住院日</td>
          <td>天</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：总院</td>
          <td>天</td>
          <td></td>
      </tr>
      <tr>
          <td>分院</td>
          <td>天</td>
          <td></td>
      </tr>
      <tr>
          <td>门诊次均费用</td>
          <td>元</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：总院</td>
          <td>元</td>
          <td></td>
      </tr>
      <tr>
          <td>分院</td>
          <td>元</td>
          <td></td>
      </tr>
      <tr>
          <td>住院次均费用</td>
          <td>元</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：总院</td>
          <td>元</td>
          <td></td>
      </tr>
      <tr>
          <td>分院</td>
          <td>元</td>
          <td></td>
      </tr>
      <tr>
          <td rowspan="28">手术及操作</td>
          <td>住院手术量合计</td>
          <td>例</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：四级手术量</td>
          <td>例</td>
          <td></td>
      </tr>
      <tr>
          <td>三级手术量</td>
          <td>例</td>
          <td></td>
      </tr>
      <tr>
          <td>二级手术量</td>
          <td>例</td>
          <td></td>
      </tr>
      <tr>
          <td>一级手术量</td>
          <td>例</td>
          <td></td>
      </tr>
      <tr>
          <td>眼科门诊手术量合计</td>
          <td>例</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：三、四级手术量</td>
          <td>例</td>
          <td></td>
      </tr>
      <tr>
          <td>耳鼻喉门诊手术量合计</td>
          <td>例</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：三、四级手术量</td>
          <td>例</td>
          <td></td>
      </tr>
      <tr>
          <td>操作例数合计</td>
          <td>例</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：导管室造影和介入操作例数小计</td>
          <td>例</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：心内</td>
          <td>例</td>
          <td></td>
      </tr>
      <tr>
          <td>神内</td>
          <td>例</td>
          <td></td>
      </tr>
      <tr>
          <td>外科</td>
          <td>例</td>
          <td></td>
      </tr>
      <tr>
          <td>消化内科</td>
          <td>例</td>
          <td></td>
      </tr>
      <tr>
          <td>神外</td>
          <td>例</td>
          <td></td>
      </tr>
      <tr>
          <td>综合科</td>
          <td>例</td>
          <td></td>
      </tr>
      <tr>
          <td>骨科</td>
          <td>例</td>
          <td></td>
      </tr>
      <tr>
          <td>呼吸内科</td>
          <td>例</td>
          <td></td>
      </tr>
      <tr>
          <td>其他</td>
          <td>例</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：胃肠镜操作小计</td>
          <td>例</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：胃镜</td>
          <td>例</td>
          <td></td>
      </tr>
      <tr>
          <td>结肠镜</td>
          <td>例</td>
          <td></td>
      </tr>
      <tr>
          <td>其他诊断治疗性操作</td>
          <td>例</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：气管镜操作小计</td>
          <td>例</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：支气管镜</td>
          <td>例</td>
          <td></td>
      </tr>
      <tr>
          <td>胸腔镜</td>
          <td>例</td>
          <td></td>
      </tr>
      <tr>
          <td>其他诊断治疗性操作</td>
          <td>例</td>
          <td></td>
      </tr>
      <tr>
          <td rowspan="2">放疗</td>
          <td>放疗例数合计</td>
          <td>例</td>
          <td></td>
      </tr>
      <tr>
          <td>放疗收入合计</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td rowspan="49">业务收入</td>
          <td>收入合计</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：财政补助收入</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：其他收入</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：医疗收入合计</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：非医疗业务收入</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：门诊收入</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>门诊药品收入</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：总院</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：不含中草药的门诊药品收入</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：分院</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：不含中草药的门诊药品收入</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>门诊医疗收入</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：总院</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：分院</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：住院收入</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>住院药品收入</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：总院</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：不含中草药的住院药品收入</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：分院</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：不含中草药的住院药品收入</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>住院医疗收入</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：总院</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：分院</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：耗材收入</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：总院</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：分院</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：体检收入</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>门诊住院收入比</td>
          <td>倍</td>
          <td></td>
      </tr>
      <tr>
          <td>门诊入院量比</td>
          <td>倍</td>
          <td></td>
      </tr>
      <tr>
          <td>当期药比</td>
          <td>%</td>
          <td></td>
      </tr>
      <tr>
          <td>不含中草药的当期药比</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：不含中草药的门诊药比</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：不含中草药的住院药比</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：分院不含中草药当期药比</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：总院药比</td>
          <td>%</td>
          <td></td>
      </tr>
      <tr>
          <td>分院药比</td>
          <td>%</td>
          <td></td>
      </tr>
      <tr>
          <td>门诊药比</td>
          <td>%</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：总院</td>
          <td>%</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：总院不含中草药的门诊药比</td>
          <td>%</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：分院</td>
          <td>%</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：分院不含中草药的门诊药比</td>
          <td>%</td>
          <td></td>
      </tr>
      <tr>
          <td>住院药比</td>
          <td>%</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：总院</td>
          <td>%</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：总院不含中草药的住院药比</td>
          <td>%</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：分院</td>
          <td>%</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：分院不含中草药的住院药比</td>
          <td>%</td>
          <td></td>
      </tr>
      <tr>
          <td>当期药耗比</td>
          <td>%</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：总院</td>
          <td>%</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：分院</td>
          <td>%</td>
          <td></td>
      </tr>
      <tr>
          <td rowspan="8">税前/考核利润</td>
          <td>报表利润</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>计提管理费</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>其他费用</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>考核利润</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：总院</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：分院</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>年度预算利润</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>完成当年预算</td>
          <td>%</td>
          <td></td>
      </tr>
      <tr>
          <td rowspan="8"></td>
          <td>总院（不含社区）医疗业务收入 </td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：门诊收入（不含社区）  </td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：门诊药品收入（不含中草药）</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：住院收入（不含社区）</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：住院药品收入（不含中草药）</td>
          <td>万元</td>
          <td></td>
      </tr>
      <tr>
          <td>总院（不含社区）不含中草药药比</td>
          <td>%</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：不含中草药的门诊药比</td>
          <td>%</td>
          <td></td>
      </tr>
      <tr>
          <td>其中：不含中草药的住院药比</td>
          <td>%</td>
          <td></td>
      </tr>
      </table>
    </div>
  </div>
</template>
<script>
import { service } from '~/plugins/axios'
import FileSaver from 'file-saver'
import XLSX from 'xlsx'

export default {
  data () {
    return {
      list: [],
      month: ''
    }
  },
  methods: {
    asyncData ({ params }) {
      console.log(params)
    },
    getData () {
      service.get('deptincome', { month: this.month }).then(response => {
        this.list = response.data
      })
    },
    indexMethod (index) {
      return ++index
    },
    exportExcel () {
      /* generate workbook object from table */
      var wb = XLSX.utils.table_to_book(document.querySelector('#exceldata'))
      /* get binary string as output */
      var wbout = XLSX.write(wb, { bookType: 'xlsx', bookSST: true, type: 'array' })
      console.log(wbout)
      try {
        FileSaver.saveAs(new Blob([wbout], { type: 'application/octet-stream' }), '科室月报.xlsx')
      } catch (e) {
        if (typeof console !== 'undefined') {
          console.log(e, wbout)
        }
      }
      return wbout
    },
    getCmonth: function () {
      let date = new Date()
      let year = date.getFullYear()
      if (date.getMonth() < 9) {
        this.month = year + '-0' + (date.getMonth() + 1)
      } else {
        this.month = year + '-' + (date.getMonth() + 1)
      }
    }
  },
  mounted () {
    this.getCmonth()
    this.getData()
  },
  computed: {
    labName: function () {
      let date = new Date(this.month)
      let name = date.getFullYear() + '年' + (date.getMonth() + 1) + '月累计'
      return name
    }
  }
}
</script>
<style>
.el-row {
  margin-bottom: 20px;
}
.el-table__footer-wrapper{
  font-weight: 600;
}
</style>
